export const themeColors = {
    backgroundColor: 'dimgray',
    buttonBorderColor: 'gainsboro',
    configBoxBorderColor: 'white',
    buttonColor: 'darkgray',
    hoverButtonColor: 'chocolate',
    inactiveButtonColor: 'sieena',
    primaryTextColor: 'white',
    secondaryTextColor: 'white',
    activeContactBackgroundColor: 'dimgray',
    configurationBoxBackgroundColor: 'darkgrey',
    configurationBoxBorderColor: '#666876',
    chatBakgroundColor: '#5c5e54',
    disabledButtonTextColor: 'burlywood',
    errorTextColor: '#C30F1A',
    errorBackgroundColor: '#830B12',
    attachmentBackgroundColor: '#202129',
    selectedContactBorderColor: 'orange',
    profileConfigurationTextColor: 'pink',
    receivedMessageBackgroundColor: 'pink',
    receivedMessageTextColor: 'white',
    sentMessageBackgroundColor: 'blue',
    sentMessageTextColor: 'white',
    infoBoxBackgroundColor: 'green',
    infoBoxTextColor: 'yellow',
    buttonShadow: '#000000',
    msgCounterBackgroundColor: 'yellow',
    msgCounterTextColor: 'white',
    scrollbarBackgroundColor: 'black',
    scrollbarScrollerColor: 'white',
    inputFieldBackgroundColor: 'saddlebrown',
    inputFieldTextColor: '#FFFF',
    inputFieldBorderColor: '#81828D',
    emojiModalBackgroundColor: '262, 240, 283', // It must be in RGB format EX: 240,248,255
    emojiModalTextColor: '102, 51, 153', // It must be in RGB format EX: 240,248,255
    emojiModalAccentColor: '255, 105, 180', // It must be in RGB format EX: 240,248,255
    rainbowConnectBtnBackgroundColor: 'blue',
    rainbowConnectBtnTextColor: 'white',
    rainbowAccentColor: 'orange',
    rainbowAccentForegroundColor: 'pink',
    rainbowModalTextColor: 'white',
    rainbowModalTextSecondaryColor: 'yellow',
    rainbowModalWalletHoverColor: 'green',
    rainbowModalBackgroundColor: 'blue',
};
